# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '__first__'),
        ('initiatives', '0022_remove_initiativeplatformsettings_search_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.Server'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='activity_search_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'location', 'Office location'), (b'country', 'Country'), (b'date', 'Date'), (b'skill', 'Skill'), (b'type', 'Type'), (b'theme', 'Theme'), (b'category', 'Category'), (b'status', 'Status')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='initiative_search_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'location', 'Office location'), (b'country', 'Country'), (b'theme', 'Theme'), (b'category', 'Category')], max_length=1000),
        ),
    ]
