# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_cellulant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellulantpayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='cellulantpayment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='cellulantpayment',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='cellulantpayment',
            name='description',
            field=models.CharField(blank=True, help_text=b'Cellulant description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cellulantpayment',
            name='payer_mode_id',
            field=models.CharField(blank=True, help_text=b'Cellulant payer mode (payment method)', max_length=200, null=True),
        ),
    ]
