# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_cellulant', '0002_auto_20180705_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellulantpayment',
            name='remote_reference',
            field=models.CharField(blank=True, help_text=b'Cellulant transaction reference', max_length=200, null=True),
        ),
    ]
