# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-10 11:07
from __future__ import unicode_literals

import bluebottle.activities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '__first__'),
        ('activities', '0020_auto_20200224_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'Organizer', 'verbose_name_plural': 'Organizers'},
        ),
        migrations.AddField(
            model_name='activity',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.Server'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.Server'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='activity',
            field=models.ForeignKey(on_delete=bluebottle.activities.models.NON_POLYMORPHIC_CASCADE, related_name='contributions', to='activities.Activity'),
        ),
    ]
