# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-10 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0001_initial'),
    ]

    operations = [
    ]
