# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0002_auto_20200310_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypubplatformsettings',
            name='public_key',
            field=models.TextField(max_length=48),
        ),
        migrations.AlterField(
            model_name='activitypubplatformsettings',
            name='secret_key',
            field=models.TextField(max_length=48),
        ),
    ]
