# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0003_auto_20200310_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalRequest',
        ),
        migrations.DeleteModel(
            name='InternalRequest',
        ),
        migrations.AddField(
            model_name='server',
            name='server_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
