# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-10 14:59
from __future__ import unicode_literals

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization


from django.db import migrations


def create_empty_settings(apps, schema_editor):
    ActivityPubPlatformSettings = apps.get_model(
        'activity_pub', 'ActivityPubPlatformSettings'
    )

    key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend()
    )
    secret_key = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    )

    public_key = key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    )

    ActivityPubPlatformSettings.objects.get_or_create(
        secret_key=secret_key,
        public_key=public_key
    )


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0004_auto_20200311_1223'),
    ]

    operations = [
        migrations.RunPython(create_empty_settings)
    ]
