# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0006_auto_20200311_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
