# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-13 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0007_auto_20200311_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='location',
            field=models.URLField(default='http://example.com', max_length=100),
            preserve_default=False,
        ),
    ]
